version: '3'
services:
  mysql:
    image: mysql
    ports:
     - 3307:3306
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123456
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 82:80
    links:
      - mysql:db
  web:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7.2-fpm
    volumes:
      - ./:/code